# Build a virtualenv using miniconda
# * Install required compilation tools for wheels via apt
# * Install required non-python binaries via conda
FROM quay.io/condaforge/miniforge3:latest AS build-venv
RUN apt -qq update && apt -qq install -y build-essential
RUN conda create -p /venv python=3.12
RUN /venv/bin/pip install --upgrade -q pip wheel setuptools
RUN conda install -p /venv -q -y eccodes 'zarr>2.18,<3'

# Build the virtualenv
# * We don't want the bufr eccodes definitions so save space by deleting them
FROM build-venv as install-reqs
RUN /venv/bin/python -m pip install -q \
    xarray ocf_blosc2 huggingface_hub \
    requests cfgrib dask google-cloud-logging
RUN rm -r /venv/share/eccodes/definitions/bufr

# Copy the virtualenv into a distroless image
FROM gcr.io/distroless/python3-debian11
COPY --from=install-reqs /venv /venv
COPY . /app
WORKDIR /app
ENTRYPOINT ["/venv/bin/python3", "download_combine_upload_icon.py"]
