# Build a virtualenv using miniconda
# * Install required compilation tools for wheels via apt
# * Install required non-python binaries via conda
FROM quay.io/condaforge/miniforge3:latest AS build-venv
RUN apt -qq update && apt -qq install -y build-essential
RUN conda create -p /venv python=3.12
RUN /venv/bin/pip install --upgrade -q pip wheel setuptools
RUN conda install -p /venv -c conda-forge -y cartopy satpy[all] eccodes numpy matplotlib rasterio
ENV GDAL_CONFIG=/venv/bin/gdal-config

# Build the virtualenv
# * We don't want the bufr eccodes definitions so save space by deleting them
FROM build-venv as install-reqs
RUN /venv/bin/python -m pip install -q satip
RUN rm -r /venv/share/eccodes/definitions/bufr


# Copy the virtualenv into a distroless image
FROM gcr.io/distroless/python3-debian11
COPY --from=install-reqs /venv /venv
COPY . /app
WORKDIR /app
ENTRYPOINT ["/venv/bin/python3", "download_process_sat.py"]

