# Build a virtualenv using miniconda
# * Install required compilation tools for wheels via apt
# * Install required non-python binaries via conda
FROM quay.io/condaforge/miniforge3:latest AS build-venv
RUN apt -qq update && apt -qq install -y build-essential
RUN conda create -p /venv python=3.12
RUN /venv/bin/pip install --upgrade -q pip wheel setuptools
RUN conda install -p /venv -c conda-forge -y cartopy satpy[all]=0.50.0 numpy
ENV GDAL_CONFIG=/venv/bin/gdal-config

# Build the virtualenv
FROM build-venv as install-reqs
RUN /venv/bin/python -m pip install -q -U diskcache pyproj \
    pyresample xarray pyyaml ocf_blosc2 eumdac requests dask zarr tqdm

# Copy the virtualenv into a distroless image
FROM gcr.io/distroless/python3-debian11
COPY --from=install-reqs /venv /venv
COPY . /app
WORKDIR /app
ENTRYPOINT ["/venv/bin/python3", "download_process_sat.py"]
VOLUME /mnt/disks/sat

