name: Build Containers

on:
  push:
    branches: []
    paths-ignore:
      - 'README.md'

# Registry for storing Container images
env:
  REGISTRY: ghcr.io

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: test-unit
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        include:
          - folder: .containers/icon
            image: ${{ env.REGISTRY }}/icon-etl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Container
        id: meta
        uses: docker/metadata-action
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: $${{ matrix.folder }}
          file: ${{ matrix.folder }}/Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

