name: Merged CI
run-name: 'Merged CI for #${{ github.event.number }}: ${{ github.event.pull_request.title }}'

on:
  pull_request:
    types: ["closed"]
    branches: [ "main" ]

jobs:
  bump-tag:
    uses: openclimatefix/.github/.github/workflows/bump_tag.yml@main
    secrets: inherit

